### ISSUE TITLE
World of Warcraft don't detect Addon.

### ISSUE THREAD

**Issue by Veecyn** [minokar/statcast#1]
Hello !
First of all thanks for your work.
i rode the news on Icy-veins about your project. I started to create my own nodeJS adaptater for Tulya devices.
I wanted to use the addon you created, so i could screen read the pixel and use it as you do.
Tho, the addon isn't detected by my game. 
Any idea of why it isn't working ?

Thanks a lot for your work and for sharing it !

**Comment by Veecyn** [comment]
Well, i found the culprit, the root name of the directory had to match with files name. 
Instead of cloning i went with the archive option.
It generated me a statcast-main directory name.
So i made both directory and files name matching and now it's detected by WoW.
Sorry about that !

**Comment by minokar** [comment]
Thanks for surfacing this! I will add a note to the README that the directory name needs to match - hadn't thought of that.
