### ISSUE TITLE
Known error in Quartz library causing failure

### ISSUE THREAD

**Issue by Archea** [minokar/statcast#4]
specifically "FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'"
after
  File "statcast.py", line 3, in <module>
    from screen_reader import ScreenReader
  File "C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\statcast-main\screen_reader.py", line 4, in <module>
    import Quartz.CoreGraphics as CG
ModuleNotFoundError: No module named 'Quartz'

Can see discusion on SO https://stackoverflow.com/questions/42530309/no-such-file-requirements-txt-error-while-installing-quartz-module

note "This won't be fixed anytime soon as it's currently abandoned due to poor architectural design."

I'm not sure what quartz is being used for. the CG variable isn't being used as far as I can see, and after removing the import it runs fine.

**Comment by minokar** [comment]
Thanks for reporting this! You're right that the Quartz imports weren't necessary -- I had forgotten to remove them after making the script multi-platform, and don't have a non-Mac device to check. :) 

Should be good now after the latest pull request, I appreciate it!
